version: '3.3'

services:
    grafana:
        ports:
            - 3000:3000
        image: grafana/grafana
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
        networks:
            - frontend
    graphite:
        image: graphiteapp/graphite-statsd
        ports:
            - 18000:80
            - 2003-2004:2003-2004
            - 2023-2024:2023-2024
            - 8125:8125/udp
            - 8126:8126
        networks:
            - frontend
            - backend
    selenium:
        image: selenium/standalone-chrome:3.141.59-oxygen
        ports:
            - 4444:4444
        volumes:
            - /dev/shm:/dev/shm
        networks:
            - browsers
    worker:
        build: .
        networks:
            - backend
            - browsers
    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - type: bind
              source: ./prometheus
              target: /etc/prometheus
        networks:
            - prometheus
            - frontend
    worker-prometheus:
        build: ./worker-prometheus
        ports:
            - 28000:8000
        networks:
            - prometheus
            - browsers
    influxdb:
        image: influxdb:1.8
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_DB=pyexample
        networks:
            - frontend
            - backend
networks:
    frontend:
    backend:
    browsers:
    prometheus:
