version: '3.3'

services:
    grafana:
        ports:
            - 3000:3000
        image: grafana/grafana
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
        networks:
            - frontend
    node-exporter:
        image: prom/node-exporter
        ports:
            - 9100:9100
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--path.rootfs=/rootfs'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        networks:
            - prometheus
    graphite:
        image: graphiteapp/graphite-statsd
        ports:
            - 18000:80
            - 2003-2004:2003-2004
            - 2023-2024:2023-2024
            - 8125:8125/udp
            - 8126:8126
        networks:
            - frontend
            - backend
    graphite-worker:
        build: .
        networks:
            - backend
            - browsers
    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - type: bind
              source: ./prometheus
              target: /etc/prometheus
            - type: volume
              source: prometheus
              target: /data
        networks:
            - prometheus
            - frontend
    worker-prometheus:
        build: ./worker-prometheus
        ports:
            - 28000:8000
        networks:
            - prometheus
            - browsers
    influxdb:
        image: influxdb:1.8
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_DB=pyexample
        networks:
            - frontend
            - backend
    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        networks:
            - prometheus
        ports:
            - 8998:8998
networks:
    frontend:
    backend:
    browsers:
    prometheus:

volumes:
  prometheus:
